name: data_app_db_only
services:
  data_app_dev_db:
    container_name: data_app_dev_db
    image: postgres:14
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d
    command: -p 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data_app
      - POSTGRES_HOST_AUTH_METHOD=trust
  data_app_prod_db:
    container_name: data_app_prod_db
    image: postgres:14
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d
    command: -p 5431
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data_app
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  pgdata_dev:
  pgdata_prod: